include: package:lint/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/models/*.dart"

linter:
  rules:
    sort_pub_dependencies: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
   