name: flutter_learn
description: Flutter Learn.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  duration: ^3.0.6
  equatable: ^2.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  fl_chart: ^0.36.1
  flutter_hooks: ^0.16.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  google_sign_in: ^5.0.4
  hooks_riverpod: ^0.14.0+3
  intl: ^0.17.0
  lint: ^1.5.3
  pedantic: ^1.11.0
  pixel_perfect: ^1.1.0
  sign_in_with_apple: ^3.0.0
  uuid: ^3.0.4

dependency_overrides: null
# analyzer: ">=0.40.0"
# intl_translation:
#   git:
#     url: git://github.com/ska2519/intl_translation
# ref: 1a18d5a676ce94918f486ef699cb479f7578fdb6
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  flutter_launcher_icons: ^0.9.0
  test: null

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: #ffffff
  # image_path: 'assets/icons/dash.png'
  image_path: 'assets/icons/dash_icon.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/pixel_perfect/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/NotoSansKR-Black.otf
          weight: 900

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          style: italic
