name: flutter_learn
description: Flutter Learn.

publish_to: 'none'

version: 0.1.19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  dcdg: ^3.1.1
  dio: ^4.0.0
  duration: ^3.0.6
  easy_localization: ^3.0.0
  equatable: ^2.0.2
  extended_image: ^4.1.0
  file_picker: ^3.0.3
  firebase_analytics: ^8.1.2
  firebase_app_check: ^0.0.1+3
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  firebase_messaging: ^10.0.3
  firebase_storage: ^9.0.0
  fl_chart: ^0.36.1
  flutter_hooks: ^0.17.0
  flutter_local_notifications: ^6.0.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  google_sign_in: ^5.0.4
  hooks_riverpod: ^0.14.0+4
  image: ^3.0.2
  image_picker: ^0.7.4
  intl: ^0.17.0
  lint: ^1.5.3
  numeral: ^1.2.4
  package_info_plus: ^1.0.3
  pedantic: ^1.11.0
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.0.0
  textfield_tags: ^1.3.1
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  youtube_player_iframe: ^2.1.0

dependency_overrides: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: 1.1.8+4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  test: null

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#428eff"
  image: assets/images/firebase_dash_splash.png
  android: true
  ios: true
  web: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
    null
  image_path: 'assets/icons/dash_icon_512.png'

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/pixel_perfect/
    - assets/translations/
    - google_fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: google_fonts/NotoSans-Regular.ttf
          weight: 700
        - asset: google_fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Regular.ttf
          weight: 400
        - asset: google_fonts/Roboto-Bold.ttf
          weight: 700

