name: Build & Deploy to Live Channel
on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v2
      # Install Flutter command
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      # Build Website
      - name: Build Website
        run:
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # PrepareReg Names
      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:flutter-learn-0225
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT PATH: ./
    
